// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ListIngredientsController from "./list_ingredients_controller"
application.register("list-ingredients", ListIngredientsController)

import ListIngredientsEditFormController from "./list_ingredients_edit_form_controller"
application.register("list-ingredients-edit-form", ListIngredientsEditFormController)
